### ISSUE TITLE
Removal of Software Clones in RobocodeEditor.java - String Template in functions CreateNewRobot and CreateNewJavaFile.

### ISSUE THREAD

**Issue by Navachethan-Murugeppa** [chiragmdeekshith/robocodeFall2024#12]
**Describe the clone**
A part of code that is reused exactly the same with no altering the code is identified. The code snippet is used twice in the same file. This follows the type 1 clone. The code is to use a string variable template that is uses classname and path name and helps in creation process that is used in creating a new robot and new file in robocode ui editor.

**Location of the clones**
robocodeFall2024\robocode.ui.editor\src\main\java\net\sf\robocode\ui\editor\RobocodeEditor.java . Where the clones are identified at the lines 166 and 389. The tow functions that has clones are CreateNewRobot() and CreateNewJavaFile().
![image](https://github.com/user-attachments/assets/25c61d3c-a638-4617-bf7e-c5bb09cffcab)

**Clone Type**
The clone is identified to be of type 1 where the code matches with minor changes to whitespaces and comments.
proof:
![image](https://github.com/user-attachments/assets/e665fe77-ea1a-44ca-95e5-89b2e7b00447)
![image](https://github.com/user-attachments/assets/36b30259-300a-49ab-ab71-b7ef6343c7f6)

**Expected outcome**
The approach is to overcome the clone by reducing the usage of code part multiple ways. One of the general approach to solve this issue is by creating a separate function and calling the function inside the mentioned functions to achieve the required task. Here a separate function is written and thus with the required parameters it is called.
![image](https://github.com/user-attachments/assets/f37c737f-8c00-4dac-b583-450a79c97e7d)

**Code before refactoring**
![image](https://github.com/user-attachments/assets/af5e67b9-060d-4f5b-b5d3-c289c464837d)

**Code after refactoring**
![image](https://github.com/user-attachments/assets/595fcab6-a0bb-4870-ac4c-5c4abe394f62)
![image](https://github.com/user-attachments/assets/1a55ebec-31ca-471e-a76f-07498dda2709)
![image](https://github.com/user-attachments/assets/927d840e-ec4a-4da5-85fa-50a7f32f2298)

**Additional context**
N/A

**Comment by chiragmdeekshith** [comment]
Closing this issue as a duplicate - because you already created it in the parent repo [here](https://github.com/rilling/robocodeFall2024/issues/28). (rilling/robocodeFall2024#28)
